version: '3'

services:
  php-fpm:
    build:
      context: ./docker
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - XDEBUG_CONFIG=client_host=host.docker.internal
