version: '3'

services:
  php-fpm:
    build:
      context: ./docker
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_IDE_CONFIG=localhost=localhost
      - XDEBUG_CONFIG=remote_host=host.docker.internal
